### PR TITLE
Switched to use YAML for config, VMS CameraRotator support

### PR DESCRIPTION
**Pull request by pkubanek**

### CODE REVIEW

**Review by dmills-lsst — COMMENTED** [review]
Is there a sleep somewhere after the salShutdown() ?

**Comment by pkubanek** [comment]
> Is there a sleep somewhere after the salShutdown() ?

Just below your question (and above mine reply). Thanks for a reminder!

**Comment by pkubanek** [comment]
obrazek
All VMS on screen.

**Review by dmills-lsst — APPROVED** [review]
ok

**Pull request merged**
